import { ActiveSkill } from '@/types/skills'

// Экспортируем тип для использования в компонентах
export type { ActiveSkill }

// Активные навыки для каждого класса
export const ACTIVE_SKILLS = {
  // Лучник
  'archer': [
    {
      id: 'archer_basic_shot',
      name: 'Точный Выстрел',
      description: 'Базовый выстрел из лука с умеренным уроном',
      level_requirement: 1,
      icon: '🏹',
      skill_type: 'active' as const,
      damage_type: 'physical' as const,
      base_damage: 80,
      mana_cost: 0,
      cooldown: 1,
      scaling_stat: 'agility' as const,
      scaling_ratio: 1.2,
      class_requirements: ['archer'],
      cost_to_learn: 0,
      is_learned: true,
      nodes: []
    },
    {
      id: 'archer_power_shot',
      name: 'Мощный Выстрел',
      description: 'Заряженный выстрел с повышенным уроном',
      level_requirement: 5,
      icon: '🎯',
      skill_type: 'active' as const,
      damage_type: 'physical' as const,
      base_damage: 150,
      mana_cost: 15,
      cooldown: 3,
      scaling_stat: 'agility' as const,
      scaling_ratio: 1.5,
      class_requirements: ['archer'],
      cost_to_learn: 100,
      is_learned: false,
      nodes: []
    },
    {
      id: 'archer_arrow_rain',
      name: 'Дождь Стрел',
      description: 'Обстреливает область несколькими стрелами',
      level_requirement: 10,
      icon: '☔',
      skill_type: 'aoe' as const,
      damage_type: 'physical' as const,
      base_damage: 120,
      mana_cost: 25,
      cooldown: 8,
      scaling_stat: 'agility' as const,
      scaling_ratio: 1.3,
      class_requirements: ['archer'],
      cost_to_learn: 500,
      is_learned: false,
      nodes: []
    },
    {
      id: 'archer_hawk_eye',
      name: 'Глаз Ястреба',
      description: 'Увеличивает точность и критический урон',
      level_requirement: 15,
      icon: '👁️',
      skill_type: 'buff' as const,
      damage_type: 'physical' as const,
      base_damage: 0,
      mana_cost: 30,
      cooldown: 15,
      scaling_stat: 'agility' as const,
      scaling_ratio: 0,
      class_requirements: ['archer'],
      cost_to_learn: 1000,
      is_learned: false,
      nodes: []
    },
    {
      id: 'archer_warding_barrier',
      name: 'Защитный Барьер',
      description: 'Создает барьер, поглощающий урон',
      level_requirement: 20,
      icon: '🛡️',
      skill_type: 'barrier' as const,
      damage_type: 'physical' as const,
      base_damage: 0,
      mana_cost: 40,
      cooldown: 20,
      scaling_stat: 'agility' as const,
      scaling_ratio: 0,
      class_requirements: ['archer'],
      cost_to_learn: 2000,
      is_learned: false,
      nodes: []
    },
    {
      id: 'archer_storm_volley',
      name: 'Штормовой Залп',
      description: 'Массивная атака с множественными выстрелами и лечением',
      level_requirement: 25,
      icon: '⛈️',
      skill_type: 'ultimate' as const,
      damage_type: 'physical' as const,
      base_damage: 300,
      mana_cost: 60,
      cooldown: 30,
      scaling_stat: 'agility' as const,
      scaling_ratio: 2.0,
      class_requirements: ['archer'],
      cost_to_learn: 5000,
      is_learned: false,
      nodes: []
    }
  ],

  // Маг
  'mage': [
    {
      id: 'mage_basic_bolt',
      name: 'Магическая Стрела',
      description: 'Базовая магическая атака',
      level_requirement: 1,
      icon: '🔮',
      skill_type: 'active' as const,
      damage_type: 'magical' as const,
      base_damage: 70,
      mana_cost: 5,
      cooldown: 1,
      scaling_stat: 'intelligence' as const,
      scaling_ratio: 1.3,
      class_requirements: ['mage'],
      cost_to_learn: 0,
      is_learned: true,
      nodes: []
    },
    {
      id: 'mage_fireball',
      name: 'Огненный Шар',
      description: 'Мощный огненный снаряд с поджогом',
      level_requirement: 5,
      icon: '🔥',
      skill_type: 'active' as const,
      damage_type: 'magical' as const,
      base_damage: 140,
      mana_cost: 20,
      cooldown: 3,
      scaling_stat: 'spell_power' as const,
      scaling_ratio: 1.6,
      class_requirements: ['mage'],
      cost_to_learn: 100,
      is_learned: false,
      nodes: []
    },
    {
      id: 'mage_chain_lightning',
      name: 'Цепная Молния',
      description: 'Молния, перескакивающая между врагами',
      level_requirement: 10,
      icon: '⚡',
      skill_type: 'aoe' as const,
      damage_type: 'magical' as const,
      base_damage: 110,
      mana_cost: 30,
      cooldown: 8,
      scaling_stat: 'spell_power' as const,
      scaling_ratio: 1.4,
      class_requirements: ['mage'],
      cost_to_learn: 500,
      is_learned: false,
      nodes: []
    },
    {
      id: 'mage_arcane_empowerment',
      name: 'Чародейское Усиление',
      description: 'Увеличивает магический урон и регенерацию маны',
      level_requirement: 15,
      icon: '✨',
      skill_type: 'buff' as const,
      damage_type: 'magical' as const,
      base_damage: 0,
      mana_cost: 35,
      cooldown: 15,
      scaling_stat: 'intelligence' as const,
      scaling_ratio: 0,
      class_requirements: ['mage'],
      cost_to_learn: 1000,
      is_learned: false,
      nodes: []
    },
    {
      id: 'mage_mana_shield',
      name: 'Мана-Щит',
      description: 'Создает щит, поглощающий урон за счет маны',
      level_requirement: 20,
      icon: '🔵',
      skill_type: 'barrier' as const,
      damage_type: 'magical' as const,
      base_damage: 0,
      mana_cost: 45,
      cooldown: 20,
      scaling_stat: 'intelligence' as const,
      scaling_ratio: 0,
      class_requirements: ['mage'],
      cost_to_learn: 2000,
      is_learned: false,
      nodes: []
    },
    {
      id: 'mage_meteor_shower',
      name: 'Метеоритный Дождь',
      description: 'Призывает метеориты на область с лечением',
      level_requirement: 25,
      icon: '☄️',
      skill_type: 'ultimate' as const,
      damage_type: 'magical' as const,
      base_damage: 280,
      mana_cost: 70,
      cooldown: 30,
      scaling_stat: 'spell_power' as const,
      scaling_ratio: 2.2,
      class_requirements: ['mage'],
      cost_to_learn: 5000,
      is_learned: false,
      nodes: []
    }
  ],

  // Берсерк
  'berserker': [
    {
      id: 'berserker_basic_strike',
      name: 'Мощный Удар',
      description: 'Базовый физический удар',
      level_requirement: 1,
      icon: '🪓',
      skill_type: 'active' as const,
      damage_type: 'physical' as const,
      base_damage: 90,
      mana_cost: 0,
      cooldown: 1,
      scaling_stat: 'strength' as const,
      scaling_ratio: 1.4,
      class_requirements: ['berserker'],
      cost_to_learn: 0,
      is_learned: true,
      nodes: []
    },
    {
      id: 'berserker_devastating_blow',
      name: 'Опустошающий Удар',
      description: 'Сокрушительная атака с высоким уроном',
      level_requirement: 5,
      icon: '💥',
      skill_type: 'active' as const,
      damage_type: 'physical' as const,
      base_damage: 180,
      mana_cost: 15,
      cooldown: 4,
      scaling_stat: 'strength' as const,
      scaling_ratio: 1.8,
      class_requirements: ['berserker'],
      cost_to_learn: 100,
      is_learned: false,
      nodes: []
    },
    {
      id: 'berserker_whirlwind',
      name: 'Смерч',
      description: 'Вращательная атака, поражающая всех вокруг',
      level_requirement: 10,
      icon: '🌪️',
      skill_type: 'aoe' as const,
      damage_type: 'physical' as const,
      base_damage: 130,
      mana_cost: 25,
      cooldown: 8,
      scaling_stat: 'strength' as const,
      scaling_ratio: 1.5,
      class_requirements: ['berserker'],
      cost_to_learn: 500,
      is_learned: false,
      nodes: []
    },
    {
      id: 'berserker_bloodlust',
      name: 'Кровожадность',
      description: 'Увеличивает физический урон и скорость атаки',
      level_requirement: 15,
      icon: '🩸',
      skill_type: 'buff' as const,
      damage_type: 'physical' as const,
      base_damage: 0,
      mana_cost: 30,
      cooldown: 15,
      scaling_stat: 'strength' as const,
      scaling_ratio: 0,
      class_requirements: ['berserker'],
      cost_to_learn: 1000,
      is_learned: false,
      nodes: []
    },
    {
      id: 'berserker_iron_skin',
      name: 'Железная Кожа',
      description: 'Временно увеличивает броню и сопротивление',
      level_requirement: 20,
      icon: '🛡️',
      skill_type: 'barrier' as const,
      damage_type: 'physical' as const,
      base_damage: 0,
      mana_cost: 40,
      cooldown: 20,
      scaling_stat: 'endurance' as const,
      scaling_ratio: 0,
      class_requirements: ['berserker'],
      cost_to_learn: 2000,
      is_learned: false,
      nodes: []
    },
    {
      id: 'berserker_apocalypse',
      name: 'Апокалипсис',
      description: 'Массивная атака с восстановлением здоровья',
      level_requirement: 25,
      icon: '💀',
      skill_type: 'ultimate' as const,
      damage_type: 'physical' as const,
      base_damage: 350,
      mana_cost: 60,
      cooldown: 30,
      scaling_stat: 'strength' as const,
      scaling_ratio: 2.5,
      class_requirements: ['berserker'],
      cost_to_learn: 5000,
      is_learned: false,
      nodes: []
    }
  ],

  // Ассасин
  'assassin': [
    {
      id: 'assassin_basic_stab',
      name: 'Быстрый Укол',
      description: 'Быстрая атака с высокой скоростью',
      level_requirement: 1,
      icon: '🗡️',
      skill_type: 'active' as const,
      damage_type: 'physical' as const,
      base_damage: 75,
      mana_cost: 0,
      cooldown: 0.8,
      scaling_stat: 'agility' as const,
      scaling_ratio: 1.3,
      class_requirements: ['assassin'],
      cost_to_learn: 0,
      is_learned: true,
      nodes: []
    },
    {
      id: 'assassin_backstab',
      name: 'Удар в Спину',
      description: 'Скрытая атака с критическим уроном',
      level_requirement: 5,
      icon: '🗡️',
      skill_type: 'active' as const,
      damage_type: 'physical' as const,
      base_damage: 160,
      mana_cost: 20,
      cooldown: 4,
      scaling_stat: 'stealth' as const,
      scaling_ratio: 1.7,
      class_requirements: ['assassin'],
      cost_to_learn: 100,
      is_learned: false,
      nodes: []
    },
    {
      id: 'assassin_poison_dart',
      name: 'Ядовитая Стрела',
      description: 'Атака с ядом, поражающая нескольких врагов',
      level_requirement: 10,
      icon: '🟢',
      skill_type: 'aoe' as const,
      damage_type: 'magical' as const,
      base_damage: 100,
      mana_cost: 25,
      cooldown: 8,
      scaling_stat: 'stealth' as const,
      scaling_ratio: 1.4,
      class_requirements: ['assassin'],
      cost_to_learn: 500,
      is_learned: false,
      nodes: []
    },
    {
      id: 'assassin_shadow_cloak',
      name: 'Теневой Плащ',
      description: 'Увеличивает скрытность и критический урон',
      level_requirement: 15,
      icon: '👤',
      skill_type: 'buff' as const,
      damage_type: 'physical' as const,
      base_damage: 0,
      mana_cost: 30,
      cooldown: 15,
      scaling_stat: 'stealth' as const,
      scaling_ratio: 0,
      class_requirements: ['assassin'],
      cost_to_learn: 1000,
      is_learned: false,
      nodes: []
    },
    {
      id: 'assassin_smoke_bomb',
      name: 'Дымовая Бомба',
      description: 'Создает дымовую завесу для защиты',
      level_requirement: 20,
      icon: '💨',
      skill_type: 'barrier' as const,
      damage_type: 'physical' as const,
      base_damage: 0,
      mana_cost: 40,
      cooldown: 20,
      scaling_stat: 'stealth' as const,
      scaling_ratio: 0,
      class_requirements: ['assassin'],
      cost_to_learn: 2000,
      is_learned: false,
      nodes: []
    },
    {
      id: 'assassin_death_mark',
      name: 'Метка Смерти',
      description: 'Массивная атака с восстановлением при убийстве',
      level_requirement: 25,
      icon: '💀',
      skill_type: 'ultimate' as const,
      damage_type: 'physical' as const,
      base_damage: 320,
      mana_cost: 60,
      cooldown: 30,
      scaling_stat: 'stealth' as const,
      scaling_ratio: 2.3,
      class_requirements: ['assassin'],
      cost_to_learn: 5000,
      is_learned: false,
      nodes: []
    }
  ]
}

// Функция для получения навыков класса
export function getClassSkills(className: string): ActiveSkill[] {
  const classKey = className.toLowerCase() as keyof typeof ACTIVE_SKILLS
  return ACTIVE_SKILLS[classKey] || []
}

// Функция для получения доступных навыков по уровню
export function getAvailableSkills(className: string, level: number): ActiveSkill[] {
  const skills = getClassSkills(className)
  return skills.map(skill => ({
    ...skill,
    is_learned: skill.level_requirement <= level
  }))
}
